#!/usr/bin/env bash
# Export a playable distribution of one project (plan11「配布形式」).
#
# Usage: ./scripts/export-game.sh <project-dir> <out-dir>
#   e.g. ./scripts/export-game.sh assets/projects/sample /tmp/my-game
#
# The output directory is self-contained:
#   deepgrid_studio        linux release binary (deepgrid_studio.exe too, if a
#                          Windows build sits at the repo root)
#   deepgrid.ron           ( play_only: true, project: "assets/projects/<name>" )
#   assets/                everything, but assets/projects/ holds ONLY the
#                          exported project — and its saves/ + *.ron.bak are
#                          excluded
#   CREDITS.md             asset credits (the title screen reads it at runtime)
#   README.md              generated, for players
#
# Bash + coreutils only (no cargo/docker): the binary must already be built
# (./docker/deepgrid-build.sh). Zip the result yourself if you need an archive.
# DEEPGRID_EXPORT_BIN overrides the binary path (used by the test suite).
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO="$(cd "$HERE/.." && pwd)"

if [[ $# -ne 2 ]]; then
  echo "usage: $0 <project-dir> <out-dir>" >&2
  exit 1
fi
SRC_PROJECT="$1"
OUT="$2"

if [[ ! -f "$SRC_PROJECT/project.ron" ]]; then
  echo "error: $SRC_PROJECT has no project.ron" >&2
  exit 1
fi
NAME="$(basename "$SRC_PROJECT")"

BIN="${DEEPGRID_EXPORT_BIN:-$REPO/target/release/deepgrid_studio}"
if [[ ! -f "$BIN" ]]; then
  echo "error: release binary not found: $BIN" >&2
  echo "build it first: ./docker/deepgrid-build.sh" >&2
  exit 1
fi

echo ">>> Exporting '$NAME' to $OUT"
mkdir -p "$OUT"

# Binary (+ optional Windows exe from ./scripts/deepgrid-run-win.sh).
cp "$BIN" "$OUT/deepgrid_studio"
chmod +x "$OUT/deepgrid_studio"
if [[ -f "$REPO/deepgrid_studio.exe" ]]; then
  cp "$REPO/deepgrid_studio.exe" "$OUT/deepgrid_studio.exe"
  echo ">>> Bundled Windows exe"
fi

# assets/ except assets/projects/ (projects are copied selectively below).
mkdir -p "$OUT/assets"
for entry in "$REPO/assets"/*; do
  base="$(basename "$entry")"
  [[ "$base" == "projects" ]] && continue
  cp -r "$entry" "$OUT/assets/$base"
done

# The exported project only, minus play-time litter: saves/ and *.ron.bak.
mkdir -p "$OUT/assets/projects"
cp -r "$SRC_PROJECT" "$OUT/assets/projects/$NAME"
rm -rf "$OUT/assets/projects/$NAME/saves"
find "$OUT/assets/projects/$NAME" -name '*.ron.bak' -delete
find "$OUT/assets" -name '*.ron.bak' -delete

# Credits (read at runtime by the title screen).
cp "$REPO/CREDITS.md" "$OUT/CREDITS.md"

# Launch config: pin the project and disable the editor / game switching.
cat > "$OUT/deepgrid.ron" <<EOF
// DeepGrid Studio distribution config (generated by export-game.sh).
(
    play_only: true,
    project: "assets/projects/$NAME",
)
EOF

# Player-facing README.
GAME_TITLE="$(sed -n 's/^ *name: *"\(.*\)",.*/\1/p' "$SRC_PROJECT/project.ron" | head -1)"
cat > "$OUT/README.md" <<EOF
# ${GAME_TITLE:-$NAME}

DeepGrid Studio 製のダンジョンRPGです。

## 遊びかた

このフォルダーで \`./deepgrid_studio\` (Windows は \`deepgrid_studio.exe\`) を
実行すると、タイトル画面からゲームを始められます。

- 移動: W/A/S/D (前後・左右)、Q/E (回転)、R/F (はしご)
- Space: ドアの開閉・調べる・攻撃 / G: 拾う / Tab: データ画面
- セーブ/ロード: データ画面のスロット、タイトルの「つづきから」
- 音量などはタイトルの「設定」から変更できます

セーブデータは \`assets/projects/$NAME/saves/\` に、
設定は \`user_settings.ron\` に保存されます。

## クレジット

利用素材の一覧は CREDITS.md を参照してください
(タイトル画面の「クレジット」でも読めます)。
EOF

echo ">>> Done: $OUT"
echo "    check: cd '$OUT' && ./deepgrid_studio"
