#!/usr/bin/env python3
"""Generate the DEEPGRID_PERF stress project (plan11「パフォーマンス」).

One level at the configured limits: 40x40 x 5 floors of dense geometry
(pillar grids, liquid strips), 48 monsters of 4 kinds and ~800 floor items —
the worst case the renderer and the cycle systems are expected to survive.

Definitions (characters / items / monsters / magics) are copied verbatim from
the sample project so they always match the current schema; only the level and
project.ron are generated. Deterministic (fixed seed) — rerunning reproduces
the same project.

Usage:
    python3 scripts/gen_stress_project.py [out_dir]   # default: assets/projects/stress
Then:
    DEEPGRID_PERF=10 ./docker/deepgrid-run.sh --project assets/projects/stress
"""

import random
import re
import shutil
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SAMPLE = REPO / "assets/projects/sample"
OUT = Path(sys.argv[1]) if len(sys.argv) > 1 else REPO / "assets/projects/stress"

W = H = 40
FLOORS = 5
MONSTERS = 48        # limits.monster_placements_per_level
MONSTER_KINDS = 4    # limits.monster_kinds_per_level
ITEMS = 800          # < limits.item_placements_per_level (1023)

random.seed(42)


def ids_in(path: Path) -> list[str]:
    """Top-level `id: "..."` occurrences of a Vec<...Def> RON file, in order."""
    return re.findall(r'id:\s*"([^"]+)"', path.read_text())


def build_floor(f: int) -> list[str]:
    """One floor: border walls, a stacked pillar grid, and liquid strips on
    floor 0 (water/fire/poison exercise the hazard scan)."""
    rows = []
    for y in range(H):
        row = []
        for x in range(W):
            c = "."
            if x in (0, W - 1) or y in (0, H - 1):
                c = "#"
            elif x % 4 == 0 and y % 4 == 0:
                c = "#"  # pillars stack across floors → lots of visible faces
            elif f == 0 and y in (14, 24, 34) and 2 <= x <= W - 3:
                c = "~^%"[y % 3]  # liquid strips
            row.append(c)
        rows.append("".join(row))
    return rows


def open_cells(rows: list[str]) -> list[tuple[int, int]]:
    return [(x, y) for y in range(H) for x in range(W) if rows[y][x] == "."]


def main() -> None:
    if not SAMPLE.is_dir():
        sys.exit(f"sample project not found: {SAMPLE}")
    if OUT.exists():
        shutil.rmtree(OUT)
    (OUT / "levels").mkdir(parents=True)

    for name in ("characters.ron", "items.ron", "monsters.ron", "magics.ron"):
        shutil.copy(SAMPLE / name, OUT / name)

    monster_ids = ids_in(OUT / "monsters.ron")[:MONSTER_KINDS]
    item_ids = ids_in(OUT / "items.ron")
    party = re.search(r"party:\s*\[([^\]]*)\]", (SAMPLE / "project.ron").read_text())
    party = party.group(1).strip() if party else ""

    floors = [build_floor(f) for f in range(FLOORS)]
    cells = open_cells(floors[0])
    # Keep the start corner clear.
    cells = [c for c in cells if c != (1, 1)]
    random.shuffle(cells)

    monsters = []
    for i in range(MONSTERS):
        x, y = cells.pop()
        mid = monster_ids[i % len(monster_ids)]
        monsters.append(f'        (id: "{mid}", x: {x}, y: {y}, floor: 0, facing: South),')

    items = []
    for i in range(ITEMS):
        x, y = cells.pop()
        iid = item_ids[i % len(item_ids)]
        items.append(f'        (id: "{iid}", x: {x}, y: {y}, floor: 0),')

    def rows_block(rows: list[str]) -> str:
        inner = "\n".join(f'            "{r}",' for r in rows)
        return f"        (rows: [\n{inner}\n        ]),"

    level = f"""// Generated by scripts/gen_stress_project.py — do not edit by hand.
(
    width: {W},
    height: {H},
    start_x: 1,
    start_y: 1,
    start_floor: 0,
    start_facing: East,
    floors: [
{chr(10).join(rows_block(r) for r in floors)}
    ],
    items: [
{chr(10).join(items)}
    ],
    monsters: [
{chr(10).join(monsters)}
    ],
    wall_texts: [],
    stairs_links: [],
    events: [],
    bgm: "bgm_dungeon1.ogg",
)
"""
    (OUT / "levels/level00.ron").write_text(level)

    project = f"""// Generated by scripts/gen_stress_project.py — do not edit by hand.
(
    name: "Stress Test",
    version: 8,
    author: "gen_stress_project.py",
    description: "DEEPGRID_PERF 計測用の上限いっぱいプロジェクト",
    limits: (
        max_levels: 14,
        floors_per_level: {FLOORS},
        floor_width: {W},
        floor_height: {H},
        door_kinds_per_level: 2,
        max_characters: 20,
        party_size: 4,
        max_item_kinds: 199,
        item_placements_per_level: 1023,
        max_monster_kinds: 56,
        monster_kinds_per_level: {MONSTER_KINDS},
        monster_placements_per_level: {MONSTERS},
        max_magic_kinds: 80,
        event_flags: 64,
        max_event_delay: 63,
        demo_message_lines: 160,
        max_demos: 6,
    ),
    levels: ["levels/level00.ron"],
    characters: "characters.ron",
    party: [{party}],
    items: "items.ron",
    monsters: "monsters.ron",
    magics: "magics.ron",
)
"""
    (OUT / "project.ron").write_text(project)
    print(f"wrote {OUT} ({MONSTERS} monsters, {ITEMS} items, {FLOORS}x{W}x{H})")


if __name__ == "__main__":
    main()
